services:
  postgres:
    image: postgres:16
    container_name: dis_ams_postgres
    environment:
      POSTGRES_DB: dis_ams
      POSTGRES_USER: dis_ams
      POSTGRES_PASSWORD: dis_ams
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data:ro
  mongodb:
    image: mongo:7
    container_name: dis_ams_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:
